/**
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient.js'
import InvoiceResponse from '../model/InvoiceResponse.js'
import PlansResponse from '../model/PlansResponse.js'
import UpdatePlanResponse from '../model/UpdatePlanResponse.js'

/**
* Billing service.
* @module api/BillingApi
* @version 0.1.0
*/
export default class BillingApi {

  /**
  * Constructs a new BillingApi.
  * @alias module:api/BillingApi
  * @class
  * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
  * default to {@link module:ApiClient#instance} if unspecified.
  */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance
  }



  /**
   * Get invoice details
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InvoiceResponse} and HTTP response
   */
  getDetailedInvoiceUsingGETWithHttpInfo(service, year, month) {
    let postBody = null

    let pathParams = {
      'service': service,
      'year': year,
      'month': month
    }
    let queryParams = {
    }
    let headerParams = {
    }
    let formParams = {
    }

    let authNames = ['api_key']
    let contentTypes = []
    let accepts = ['application/json']
    let returnType = InvoiceResponse

    return this.apiClient.callApi(
      '/users-web/api/v3/billing/invoice/{service}/{year}/{month}', 'GET',
      pathParams, queryParams, headerParams, formParams, postBody,
      authNames, contentTypes, accepts, returnType
    )
  }

  /**
   * Get invoice details
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InvoiceResponse}
   */
  getDetailedInvoiceUsingGET(service, year, month) {
    return this.getDetailedInvoiceUsingGETWithHttpInfo(service, year, month)
      .then(function (response_and_data) {
        return response_and_data.data
      })
  }


  /**
   * Get available plans
   * @param {Object} opts Optional parameters
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PlansResponse} and HTTP response
   */
  listAvailablePlansUsingGETWithHttpInfo(opts) {
    opts = opts || {}
    let postBody = null

    let pathParams = {
    }
    let queryParams = {
      'integrationId': opts['integrationId'],
      'appType': opts['appType']
    }
    let headerParams = {
    }
    let formParams = {
    }

    let authNames = ['api_key']
    let contentTypes = []
    let accepts = ['application/json']
    let returnType = PlansResponse

    return this.apiClient.callApi(
      '/users-web/api/v3/billing/availablePlans', 'GET',
      pathParams, queryParams, headerParams, formParams, postBody,
      authNames, contentTypes, accepts, returnType
    )
  }

  /**
   * Get available plans
   * @param {Object} opts Optional parameters
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PlansResponse}
   */
  listAvailablePlansUsingGET(opts) {
    return this.listAvailablePlansUsingGETWithHttpInfo(opts)
      .then(function (response_and_data) {
        return response_and_data.data
      })
  }


  /**
   * Update plan for an app
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UpdatePlanResponse} and HTTP response
   */
  updatePlanUsingPUTWithHttpInfo(body, appId) {
    let postBody = body

    let pathParams = {
      'appId': appId
    }
    let queryParams = {
    }
    let headerParams = {
    }
    let formParams = {
    }

    let authNames = ['api_key']
    let contentTypes = ['application/json']
    let accepts = ['application/json']
    let returnType = UpdatePlanResponse

    return this.apiClient.callApi(
      '/users-web/api/v3/billing/info/{appId}', 'PUT',
      pathParams, queryParams, headerParams, formParams, postBody,
      authNames, contentTypes, accepts, returnType
    )
  }

  /**
   * Update plan for an app
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UpdatePlanResponse}
   */
  updatePlanUsingPUT(body, appId) {
    return this.updatePlanUsingPUTWithHttpInfo(body, appId)
      .then(function (response_and_data) {
        return response_and_data.data
      })
  }

}
