/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SematextCloudApi) {
      root.SematextCloudApi = {};
    }
    root.SematextCloudApi.AlertRuleScheduleTimeRangeDto = factory(root.SematextCloudApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The AlertRuleScheduleTimeRangeDto model module.
   * @module model/AlertRuleScheduleTimeRangeDto
   * @version v3
   */

  /**
   * Constructs a new <code>AlertRuleScheduleTimeRangeDto</code>.
   * @alias module:model/AlertRuleScheduleTimeRangeDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AlertRuleScheduleTimeRangeDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AlertRuleScheduleTimeRangeDto} obj Optional instance to populate.
   * @return {module:model/AlertRuleScheduleTimeRangeDto} The populated <code>AlertRuleScheduleTimeRangeDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'String');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} end
   */
  exports.prototype.end = undefined;

  /**
   * @member {String} start
   */
  exports.prototype.start = undefined;

  return exports;

}));
