/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AlertRuleScheduleTimeRangeDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AlertRuleScheduleTimeRangeDto'));
  } else {
    // Browser globals (root is window)
    if (!root.SematextCloudApi) {
      root.SematextCloudApi = {};
    }
    root.SematextCloudApi.AlertRuleScheduleWeekdayDto = factory(root.SematextCloudApi.ApiClient, root.SematextCloudApi.AlertRuleScheduleTimeRangeDto);
  }
}(this, function(ApiClient, AlertRuleScheduleTimeRangeDto) {
  'use strict';

  /**
   * The AlertRuleScheduleWeekdayDto model module.
   * @module model/AlertRuleScheduleWeekdayDto
   * @version v3
   */

  /**
   * Constructs a new <code>AlertRuleScheduleWeekdayDto</code>.
   * @alias module:model/AlertRuleScheduleWeekdayDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AlertRuleScheduleWeekdayDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AlertRuleScheduleWeekdayDto} obj Optional instance to populate.
   * @return {module:model/AlertRuleScheduleWeekdayDto} The populated <code>AlertRuleScheduleWeekdayDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('day'))
        obj.day = ApiClient.convertToType(data['day'], 'String');
      if (data.hasOwnProperty('index'))
        obj.index = ApiClient.convertToType(data['index'], 'Number');
      if (data.hasOwnProperty('intervals'))
        obj.intervals = ApiClient.convertToType(data['intervals'], [AlertRuleScheduleTimeRangeDto]);
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} day
   */
  exports.prototype.day = undefined;

  /**
   * @member {Number} index
   */
  exports.prototype.index = undefined;

  /**
   * @member {Array.<module:model/AlertRuleScheduleTimeRangeDto>} intervals
   */
  exports.prototype.intervals = undefined;

  /**
   * @member {String} label
   */
  exports.prototype.label = undefined;

  /**
   * @member {String} type
   */
  exports.prototype.type = undefined;

  return exports;

}));
