/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Error'));
  } else {
    // Browser globals (root is window)
    if (!root.SematextCloudApi) {
      root.SematextCloudApi = {};
    }
    root.SematextCloudApi.GenericApiResponse = factory(root.SematextCloudApi.ApiClient, root.SematextCloudApi.Error);
  }
}(this, function(ApiClient, Error) {
  'use strict';

  /**
   * The GenericApiResponse model module.
   * @module model/GenericApiResponse
   * @version v3
   */

  /**
   * Constructs a new <code>GenericApiResponse</code>.
   * Generic wrapper class for all API responses
   * @alias module:model/GenericApiResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>GenericApiResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GenericApiResponse} obj Optional instance to populate.
   * @return {module:model/GenericApiResponse} The populated <code>GenericApiResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], Object);
      if (data.hasOwnProperty('errors'))
        obj.errors = ApiClient.convertToType(data['errors'], [Error]);
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
    }
    return obj;
  }

  /**
   * Contains actual data when response is successful. Key and Value is specific to each endpoint
   * @member {Object} data
   */
  exports.prototype.data = undefined;

  /**
   * @member {Array.<module:model/Error>} errors
   */
  exports.prototype.errors = undefined;

  /**
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * @member {Boolean} success
   */
  exports.prototype.success = undefined;

  return exports;

}));
