/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GenericApiResponse', 'model/SavedQuery'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GenericApiResponse'), require('../model/SavedQuery'));
  } else {
    // Browser globals (root is window)
    if (!root.SematextCloudApi) {
      root.SematextCloudApi = {};
    }
    root.SematextCloudApi.SavedQueriesApi = factory(root.SematextCloudApi.ApiClient, root.SematextCloudApi.GenericApiResponse, root.SematextCloudApi.SavedQuery);
  }
}(this, function(ApiClient, GenericApiResponse, SavedQuery) {
  'use strict';

  /**
   * SavedQueries service.
   * @module api/SavedQueriesApi
   * @version v3
   */

  /**
   * Constructs a new SavedQueriesApi. 
   * @alias module:api/SavedQueriesApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the deleteSavedQueryUsingDELETE operation.
     * @callback module:api/SavedQueriesApi~deleteSavedQueryUsingDELETECallback
     * @param {String} error Error message, if any.
     * @param {module:model/GenericApiResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete saved query
     * @param {Number} updateableQueryId updateableQueryId
     * @param {module:api/SavedQueriesApi~deleteSavedQueryUsingDELETECallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GenericApiResponse}
     */
    this.deleteSavedQueryUsingDELETE = function(updateableQueryId, callback) {
      var postBody = null;

      // verify the required parameter 'updateableQueryId' is set
      if (updateableQueryId === undefined || updateableQueryId === null) {
        throw new Error("Missing the required parameter 'updateableQueryId' when calling deleteSavedQueryUsingDELETE");
      }


      var pathParams = {
        'updateableQueryId': updateableQueryId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GenericApiResponse;

      return this.apiClient.callApi(
        '/users-web/api/v3/savedQueries/{updateableQueryId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSavedQueriesForAppUsingGET operation.
     * @callback module:api/SavedQueriesApi~getSavedQueriesForAppUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GenericApiResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get saved queries for an app
     * @param {Number} appId appId
     * @param {module:api/SavedQueriesApi~getSavedQueriesForAppUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GenericApiResponse}
     */
    this.getSavedQueriesForAppUsingGET = function(appId, callback) {
      var postBody = null;

      // verify the required parameter 'appId' is set
      if (appId === undefined || appId === null) {
        throw new Error("Missing the required parameter 'appId' when calling getSavedQueriesForAppUsingGET");
      }


      var pathParams = {
        'appId': appId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GenericApiResponse;

      return this.apiClient.callApi(
        '/users-web/api/v3/apps/{appId}/savedQueries', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the saveQueryUsingPOST operation.
     * @callback module:api/SavedQueriesApi~saveQueryUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GenericApiResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create saved query
     * @param {module:model/SavedQuery} savedQueryDto savedQueryDto
     * @param {module:api/SavedQueriesApi~saveQueryUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GenericApiResponse}
     */
    this.saveQueryUsingPOST = function(savedQueryDto, callback) {
      var postBody = savedQueryDto;

      // verify the required parameter 'savedQueryDto' is set
      if (savedQueryDto === undefined || savedQueryDto === null) {
        throw new Error("Missing the required parameter 'savedQueryDto' when calling saveQueryUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GenericApiResponse;

      return this.apiClient.callApi(
        '/users-web/api/v3/savedQueries', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the saveQueryUsingPUT operation.
     * @callback module:api/SavedQueriesApi~saveQueryUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GenericApiResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update saved query
     * @param {module:model/SavedQuery} savedQueryDto savedQueryDto
     * @param {Number} updateableQueryId updateableQueryId
     * @param {module:api/SavedQueriesApi~saveQueryUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GenericApiResponse}
     */
    this.saveQueryUsingPUT = function(savedQueryDto, updateableQueryId, callback) {
      var postBody = savedQueryDto;

      // verify the required parameter 'savedQueryDto' is set
      if (savedQueryDto === undefined || savedQueryDto === null) {
        throw new Error("Missing the required parameter 'savedQueryDto' when calling saveQueryUsingPUT");
      }

      // verify the required parameter 'updateableQueryId' is set
      if (updateableQueryId === undefined || updateableQueryId === null) {
        throw new Error("Missing the required parameter 'updateableQueryId' when calling saveQueryUsingPUT");
      }


      var pathParams = {
        'updateableQueryId': updateableQueryId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GenericApiResponse;

      return this.apiClient.callApi(
        '/users-web/api/v3/savedQueries/{updateableQueryId}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
