/**
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SematextApiClientJavascript);
  }
}(this, function (expect, SematextApiClientJavascript) {
  'use strict';

  var instance;

  beforeEach(function () {
    instance = new SematextApiClientJavascript.NotificationIntegration();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NotificationIntegration', function () {
    it('should create an instance of NotificationIntegration', function () {
      // uncomment below and update the code to test NotificationIntegration
      //var instane = new SematextApiClientJavascript.NotificationIntegration();
      //expect(instance).to.be.a(SematextApiClientJavascript.NotificationIntegration);
    });

    it('should have the property applicability (base name: "applicability")', function () {
      // uncomment below and update the code to test the property applicability
      //var instane = new SematextApiClientJavascript.NotificationIntegration();
      //expect(instance).to.be();
    });

    it('should have the property createDate (base name: "createDate")', function () {
      // uncomment below and update the code to test the property createDate
      //var instane = new SematextApiClientJavascript.NotificationIntegration();
      //expect(instance).to.be();
    });

    it('should have the property createdByOwner (base name: "createdByOwner")', function () {
      // uncomment below and update the code to test the property createdByOwner
      //var instane = new SematextApiClientJavascript.NotificationIntegration();
      //expect(instance).to.be();
    });

    it('should have the property creatorId (base name: "creatorId")', function () {
      // uncomment below and update the code to test the property creatorId
      //var instane = new SematextApiClientJavascript.NotificationIntegration();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function () {
      // uncomment below and update the code to test the property id
      //var instane = new SematextApiClientJavascript.NotificationIntegration();
      //expect(instance).to.be();
    });

    it('should have the property integrationType (base name: "integrationType")', function () {
      // uncomment below and update the code to test the property integrationType
      //var instane = new SematextApiClientJavascript.NotificationIntegration();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function () {
      // uncomment below and update the code to test the property name
      //var instane = new SematextApiClientJavascript.NotificationIntegration();
      //expect(instance).to.be();
    });

    it('should have the property params (base name: "params")', function () {
      // uncomment below and update the code to test the property params
      //var instane = new SematextApiClientJavascript.NotificationIntegration();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function () {
      // uncomment below and update the code to test the property state
      //var instane = new SematextApiClientJavascript.NotificationIntegration();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "userId")', function () {
      // uncomment below and update the code to test the property userId
      //var instane = new SematextApiClientJavascript.NotificationIntegration();
      //expect(instance).to.be();
    });

  });

}));
