/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../stcloud/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../stcloud/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SematextApiClientJavascript);
  }
}(this, function(expect, SematextApiClientJavascript) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AppMetadata', function() {
      beforeEach(function() {
        instance = new SematextApiClientJavascript.AppMetadata();
      });

      it('should create an instance of AppMetadata', function() {
        // TODO: update the code to test AppMetadata
        expect(instance).to.be.a(SematextApiClientJavascript.AppMetadata);
      });

      it('should have the property awsCloudWatchAccessKey (base name: "awsCloudWatchAccessKey")', function() {
        // TODO: update the code to test the property awsCloudWatchAccessKey
        expect(instance).to.have.property('awsCloudWatchAccessKey');
        // expect(instance.awsCloudWatchAccessKey).to.be(expectedValueLiteral);
      });

      it('should have the property awsCloudWatchSecretKey (base name: "awsCloudWatchSecretKey")', function() {
        // TODO: update the code to test the property awsCloudWatchSecretKey
        expect(instance).to.have.property('awsCloudWatchSecretKey');
        // expect(instance.awsCloudWatchSecretKey).to.be(expectedValueLiteral);
      });

      it('should have the property awsFetchFrequency (base name: "awsFetchFrequency")', function() {
        // TODO: update the code to test the property awsFetchFrequency
        expect(instance).to.have.property('awsFetchFrequency');
        // expect(instance.awsFetchFrequency).to.be(expectedValueLiteral);
      });

      it('should have the property awsRegion (base name: "awsRegion")', function() {
        // TODO: update the code to test the property awsRegion
        expect(instance).to.have.property('awsRegion');
        // expect(instance.awsRegion).to.be(expectedValueLiteral);
      });

      it('should have the property subTypes (base name: "subTypes")', function() {
        // TODO: update the code to test the property subTypes
        expect(instance).to.have.property('subTypes');
        // expect(instance.subTypes).to.be(expectedValueLiteral);
      });

    });
  });

}));
