/**
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../api/ApiClient.js'
import AlertRuleScheduleTimeRangeDto from './AlertRuleScheduleTimeRangeDto.js'

/**
* The AlertRuleScheduleWeekdayDto model module.
* @module model/AlertRuleScheduleWeekdayDto
* @version 0.1.0
*/
export default class AlertRuleScheduleWeekdayDto {
  /**
    * Constructs a new <code>AlertRuleScheduleWeekdayDto</code>.
    * @alias module:model/AlertRuleScheduleWeekdayDto
    * @class
    */

  constructor() {



  }

  /**
    * Constructs a <code>AlertRuleScheduleWeekdayDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AlertRuleScheduleWeekdayDto} obj Optional instance to populate.
    * @return {module:model/AlertRuleScheduleWeekdayDto} The populated <code>AlertRuleScheduleWeekdayDto</code> instance.
    */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AlertRuleScheduleWeekdayDto()


      if (Object.prototype.hasOwnProperty.call(data,'day')) {
        obj['day'] = ApiClient.convertToType(data['day'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'index')) {
        obj['index'] = ApiClient.convertToType(data['index'], 'Number')
      }
      if (Object.prototype.hasOwnProperty.call(data,'intervals')) {
        obj['intervals'] = ApiClient.convertToType(data['intervals'], [AlertRuleScheduleTimeRangeDto])
      }
      if (Object.prototype.hasOwnProperty.call(data,'label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String')
      }
    }
    return obj
  }

    /**
    * @member {String} day
    */
    'day' = undefined;
    /**
    * @member {Number} index
    */
    'index' = undefined;
    /**
    * @member {Array.<module:model/AlertRuleScheduleTimeRangeDto>} intervals
    */
    'intervals' = undefined;
    /**
    * @member {String} label
    */
    'label' = undefined;
    /**
    * @member {String} type
    */
    'type' = undefined;




}
