/**
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../api/ApiClient.js'
import AlertRuleScheduleWeekdayDto from './AlertRuleScheduleWeekdayDto.js'
import FilterValue from './FilterValue.js'
import NotificationIntegration from './NotificationIntegration.js'
import UserPermissions from './UserPermissions.js'

/**
* The AlertRule model module.
* @module model/AlertRule
* @version 0.1.0
*/
export default class AlertRule {
  /**
    * Constructs a new <code>AlertRule</code>.
    * @alias module:model/AlertRule
    * @class
    */

  constructor() {



  }

  /**
    * Constructs a <code>AlertRule</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AlertRule} obj Optional instance to populate.
    * @return {module:model/AlertRule} The populated <code>AlertRule</code> instance.
    */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AlertRule()


      if (Object.prototype.hasOwnProperty.call(data,'accountEmail')) {
        obj['accountEmail'] = ApiClient.convertToType(data['accountEmail'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'allowedAppTypes')) {
        obj['allowedAppTypes'] = ApiClient.convertToType(data['allowedAppTypes'], ['Number'])
      }
      if (Object.prototype.hasOwnProperty.call(data,'analyzingTime')) {
        obj['analyzingTime'] = ApiClient.convertToType(data['analyzingTime'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'appDisplayState')) {
        obj['appDisplayState'] = ApiClient.convertToType(data['appDisplayState'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'appId')) {
        obj['appId'] = ApiClient.convertToType(data['appId'], 'Number')
      }
      if (Object.prototype.hasOwnProperty.call(data,'appName')) {
        obj['appName'] = ApiClient.convertToType(data['appName'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'appState')) {
        obj['appState'] = ApiClient.convertToType(data['appState'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'appToken')) {
        obj['appToken'] = ApiClient.convertToType(data['appToken'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'appType')) {
        obj['appType'] = ApiClient.convertToType(data['appType'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'backToNormalNeeded')) {
        obj['backToNormalNeeded'] = ApiClient.convertToType(data['backToNormalNeeded'], 'Boolean')
      }
      if (Object.prototype.hasOwnProperty.call(data,'chartKey')) {
        obj['chartKey'] = ApiClient.convertToType(data['chartKey'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'color')) {
        obj['color'] = ApiClient.convertToType(data['color'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'creatorEmail')) {
        obj['creatorEmail'] = ApiClient.convertToType(data['creatorEmail'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'defaultAggType')) {
        obj['defaultAggType'] = ApiClient.convertToType(data['defaultAggType'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'disallowedAppTypes')) {
        obj['disallowedAppTypes'] = ApiClient.convertToType(data['disallowedAppTypes'], ['Number'])
      }
      if (Object.prototype.hasOwnProperty.call(data,'enabled')) {
        obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean')
      }
      if (Object.prototype.hasOwnProperty.call(data,'estimateOperation')) {
        obj['estimateOperation'] = ApiClient.convertToType(data['estimateOperation'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'estimateValue')) {
        obj['estimateValue'] = ApiClient.convertToType(data['estimateValue'], 'Number')
      }
      if (Object.prototype.hasOwnProperty.call(data,'filterValues')) {
        obj['filterValues'] = ApiClient.convertToType(data['filterValues'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'filterValuesObj')) {
        obj['filterValuesObj'] = ApiClient.convertToType(data['filterValuesObj'], [FilterValue])
      }
      if (Object.prototype.hasOwnProperty.call(data,'ignoreRegularEventsEnabled')) {
        obj['ignoreRegularEventsEnabled'] = ApiClient.convertToType(data['ignoreRegularEventsEnabled'], 'Boolean')
      }
      if (Object.prototype.hasOwnProperty.call(data,'integrations')) {
        obj['integrations'] = ApiClient.convertToType(data['integrations'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'lastDataReceivedDate')) {
        obj['lastDataReceivedDate'] = ApiClient.convertToType(data['lastDataReceivedDate'], 'Number')
      }
      if (Object.prototype.hasOwnProperty.call(data,'lastSent')) {
        obj['lastSent'] = ApiClient.convertToType(data['lastSent'], 'Number')
      }
      if (Object.prototype.hasOwnProperty.call(data,'lastTriggered')) {
        obj['lastTriggered'] = ApiClient.convertToType(data['lastTriggered'], 'Number')
      }
      if (Object.prototype.hasOwnProperty.call(data,'metadata')) {
        obj['metadata'] = ApiClient.convertToType(data['metadata'], Object)
      }
      if (Object.prototype.hasOwnProperty.call(data,'metricKey')) {
        obj['metricKey'] = ApiClient.convertToType(data['metricKey'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'metricLabel')) {
        obj['metricLabel'] = ApiClient.convertToType(data['metricLabel'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'minDelayBetweenNotificationsInMinutes')) {
        obj['minDelayBetweenNotificationsInMinutes'] = ApiClient.convertToType(data['minDelayBetweenNotificationsInMinutes'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'notificationEmails')) {
        obj['notificationEmails'] = ApiClient.convertToType(data['notificationEmails'], ['String'])
      }
      if (Object.prototype.hasOwnProperty.call(data,'notificationIntegrations')) {
        obj['notificationIntegrations'] = ApiClient.convertToType(data['notificationIntegrations'], [NotificationIntegration])
      }
      if (Object.prototype.hasOwnProperty.call(data,'notificationsEnabled')) {
        obj['notificationsEnabled'] = ApiClient.convertToType(data['notificationsEnabled'], 'Boolean')
      }
      if (Object.prototype.hasOwnProperty.call(data,'query')) {
        obj['query'] = ApiClient.convertToType(data['query'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'reportName')) {
        obj['reportName'] = ApiClient.convertToType(data['reportName'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'ruleKey')) {
        obj['ruleKey'] = ApiClient.convertToType(data['ruleKey'], 'Number')
      }
      if (Object.prototype.hasOwnProperty.call(data,'ruleType')) {
        obj['ruleType'] = ApiClient.convertToType(data['ruleType'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'runbook')) {
        obj['runbook'] = ApiClient.convertToType(data['runbook'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'savedQueryId')) {
        obj['savedQueryId'] = ApiClient.convertToType(data['savedQueryId'], 'Number')
      }
      if (Object.prototype.hasOwnProperty.call(data,'schedule')) {
        obj['schedule'] = ApiClient.convertToType(data['schedule'], [AlertRuleScheduleWeekdayDto])
      }
      if (Object.prototype.hasOwnProperty.call(data,'sematextService')) {
        obj['sematextService'] = ApiClient.convertToType(data['sematextService'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'sendToEmail')) {
        obj['sendToEmail'] = ApiClient.convertToType(data['sendToEmail'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'timezone')) {
        obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'useOnlyAlertRuleIntegrations')) {
        obj['useOnlyAlertRuleIntegrations'] = ApiClient.convertToType(data['useOnlyAlertRuleIntegrations'], 'Boolean')
      }
      if (Object.prototype.hasOwnProperty.call(data,'userPermissions')) {
        obj['userPermissions'] = UserPermissions.constructFromObject(data['userPermissions'])
      }
      if (Object.prototype.hasOwnProperty.call(data,'valueColumnName')) {
        obj['valueColumnName'] = ApiClient.convertToType(data['valueColumnName'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'valueName')) {
        obj['valueName'] = ApiClient.convertToType(data['valueName'], 'String')
      }
    }
    return obj
  }

    /**
    * @member {String} accountEmail
    */
    'accountEmail' = undefined;
    /**
    * @member {Array.<Number>} allowedAppTypes
    */
    'allowedAppTypes' = undefined;
    /**
    * @member {String} analyzingTime
    */
    'analyzingTime' = undefined;
    /**
    * @member {String} appDisplayState
    */
    'appDisplayState' = undefined;
    /**
    * @member {Number} appId
    */
    'appId' = undefined;
    /**
    * @member {String} appName
    */
    'appName' = undefined;
    /**
    * @member {String} appState
    */
    'appState' = undefined;
    /**
    * @member {String} appToken
    */
    'appToken' = undefined;
    /**
    * @member {String} appType
    */
    'appType' = undefined;
    /**
    * @member {Boolean} backToNormalNeeded
    */
    'backToNormalNeeded' = undefined;
    /**
    * @member {String} chartKey
    */
    'chartKey' = undefined;
    /**
    * @member {String} color
    */
    'color' = undefined;
    /**
    * @member {String} creatorEmail
    */
    'creatorEmail' = undefined;
    /**
    * @member {String} defaultAggType
    */
    'defaultAggType' = undefined;
    /**
    * @member {String} description
    */
    'description' = undefined;
    /**
    * @member {Array.<Number>} disallowedAppTypes
    */
    'disallowedAppTypes' = undefined;
    /**
    * @member {Boolean} enabled
    */
    'enabled' = undefined;
    /**
    * @member {module:model/AlertRule.EstimateOperationEnum} estimateOperation
    */
    'estimateOperation' = undefined;
    /**
    * @member {Number} estimateValue
    */
    'estimateValue' = undefined;
    /**
    * @member {String} filterValues
    */
    'filterValues' = undefined;
    /**
    * @member {Array.<module:model/FilterValue>} filterValuesObj
    */
    'filterValuesObj' = undefined;
    /**
    * @member {Boolean} ignoreRegularEventsEnabled
    */
    'ignoreRegularEventsEnabled' = undefined;
    /**
    * @member {String} integrations
    */
    'integrations' = undefined;
    /**
    * @member {Number} lastDataReceivedDate
    */
    'lastDataReceivedDate' = undefined;
    /**
    * @member {Number} lastSent
    */
    'lastSent' = undefined;
    /**
    * @member {Number} lastTriggered
    */
    'lastTriggered' = undefined;
    /**
    * @member {Object} metadata
    */
    'metadata' = undefined;
    /**
    * @member {String} metricKey
    */
    'metricKey' = undefined;
    /**
    * @member {String} metricLabel
    */
    'metricLabel' = undefined;
    /**
    * @member {String} minDelayBetweenNotificationsInMinutes
    */
    'minDelayBetweenNotificationsInMinutes' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {Array.<String>} notificationEmails
    */
    'notificationEmails' = undefined;
    /**
    * @member {Array.<module:model/NotificationIntegration>} notificationIntegrations
    */
    'notificationIntegrations' = undefined;
    /**
    * @member {Boolean} notificationsEnabled
    */
    'notificationsEnabled' = undefined;
    /**
    * @member {String} query
    */
    'query' = undefined;
    /**
    * @member {String} reportName
    */
    'reportName' = undefined;
    /**
    * @member {Number} ruleKey
    */
    'ruleKey' = undefined;
    /**
    * @member {String} ruleType
    */
    'ruleType' = undefined;
    /**
    * @member {String} runbook
    */
    'runbook' = undefined;
    /**
    * @member {Number} savedQueryId
    */
    'savedQueryId' = undefined;
    /**
    * @member {Array.<module:model/AlertRuleScheduleWeekdayDto>} schedule
    */
    'schedule' = undefined;
    /**
    * @member {String} sematextService
    */
    'sematextService' = undefined;
    /**
    * @member {String} sendToEmail
    */
    'sendToEmail' = undefined;
    /**
    * @member {String} timezone
    */
    'timezone' = undefined;
    /**
    * @member {Boolean} useOnlyAlertRuleIntegrations
    */
    'useOnlyAlertRuleIntegrations' = undefined;
    /**
    * @member {module:model/UserPermissions} userPermissions
    */
    'userPermissions' = undefined;
    /**
    * @member {String} valueColumnName
    */
    'valueColumnName' = undefined;
    /**
    * @member {String} valueName
    */
    'valueName' = undefined;



    /**
    * Allowed values for the <code>estimateOperation</code> property.
    * @enum {String}
    * @readonly
    */
    static EstimateOperationEnum = {
      /**
         * value: "LESS"
         * @const
         */
      'LESS': 'LESS',
      /**
         * value: "MORE"
         * @const
         */
      'MORE': 'MORE',
      /**
         * value: "EQUAL"
         * @const
         */
      'EQUAL': 'EQUAL',
      /**
         * value: "UN_EQUAL"
         * @const
         */
      'UN_EQUAL': 'UN_EQUAL',
      /**
         * value: "LESS_OR_EQUAL"
         * @const
         */
      'LESS_OR_EQUAL': 'LESS_OR_EQUAL',
      /**
         * value: "MORE_OR_EQUAL"
         * @const
         */
      'MORE_OR_EQUAL': 'MORE_OR_EQUAL'
    };

}
