/**
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BasicOrganizationDto from './BasicOrganizationDto';
import Plan from './Plan';
import ServiceIntegration from './ServiceIntegration';
import UserRole from './UserRole';

/**
* The App model module.
* @module model/App
* @version 0.1.0
*/
export default class App {
    /**
    * Constructs a new <code>App</code>.
    * @alias module:model/App
    * @class
    */

    constructor() {



    }

    /**
    * Constructs a <code>App</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/App} obj Optional instance to populate.
    * @return {module:model/App} The populated <code>App</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new App();


            if (data.hasOwnProperty('ajaxThreshold')) {
                obj['ajaxThreshold'] = ApiClient.convertToType(data['ajaxThreshold'], 'Number');
            }
            if (data.hasOwnProperty('appType')) {
                obj['appType'] = ApiClient.convertToType(data['appType'], 'String');
            }
            if (data.hasOwnProperty('appTypeId')) {
                obj['appTypeId'] = ApiClient.convertToType(data['appTypeId'], 'Number');
            }
            if (data.hasOwnProperty('creatorEmail')) {
                obj['creatorEmail'] = ApiClient.convertToType(data['creatorEmail'], 'String');
            }
            if (data.hasOwnProperty('creditCardExpiry')) {
                obj['creditCardExpiry'] = ApiClient.convertToType(data['creditCardExpiry'], 'String');
            }
            if (data.hasOwnProperty('creditCardNumber')) {
                obj['creditCardNumber'] = ApiClient.convertToType(data['creditCardNumber'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('displayStatus')) {
                obj['displayStatus'] = ApiClient.convertToType(data['displayStatus'], 'String');
            }
            if (data.hasOwnProperty('firstDataSavedDate')) {
                obj['firstDataSavedDate'] = ApiClient.convertToType(data['firstDataSavedDate'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('integration')) {
                obj['integration'] = ServiceIntegration.constructFromObject(data['integration']);
            }
            if (data.hasOwnProperty('lastDataReceivedDate')) {
                obj['lastDataReceivedDate'] = ApiClient.convertToType(data['lastDataReceivedDate'], 'Number');
            }
            if (data.hasOwnProperty('lastDataSavedDate')) {
                obj['lastDataSavedDate'] = ApiClient.convertToType(data['lastDataSavedDate'], 'Number');
            }
            if (data.hasOwnProperty('loggedInUserAppRole')) {
                obj['loggedInUserAppRole'] = ApiClient.convertToType(data['loggedInUserAppRole'], 'String');
            }
            if (data.hasOwnProperty('monthlyInvoiceAccount')) {
                obj['monthlyInvoiceAccount'] = ApiClient.convertToType(data['monthlyInvoiceAccount'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('ownerEmail')) {
                obj['ownerEmail'] = ApiClient.convertToType(data['ownerEmail'], 'String');
            }
            if (data.hasOwnProperty('owningOrganization')) {
                obj['owningOrganization'] = BasicOrganizationDto.constructFromObject(data['owningOrganization']);
            }
            if (data.hasOwnProperty('pageLoadThreshold')) {
                obj['pageLoadThreshold'] = ApiClient.convertToType(data['pageLoadThreshold'], 'Number');
            }
            if (data.hasOwnProperty('paymentMethodId')) {
                obj['paymentMethodId'] = ApiClient.convertToType(data['paymentMethodId'], 'Number');
            }
            if (data.hasOwnProperty('plan')) {
                obj['plan'] = Plan.constructFromObject(data['plan']);
            }
            if (data.hasOwnProperty('prepaidAccount')) {
                obj['prepaidAccount'] = ApiClient.convertToType(data['prepaidAccount'], 'Boolean');
            }
            if (data.hasOwnProperty('readToken')) {
                obj['readToken'] = ApiClient.convertToType(data['readToken'], 'String');
            }
            if (data.hasOwnProperty('readWriteToken')) {
                obj['readWriteToken'] = ApiClient.convertToType(data['readWriteToken'], 'String');
            }
            if (data.hasOwnProperty('registrationDate')) {
                obj['registrationDate'] = ApiClient.convertToType(data['registrationDate'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('tokens')) {
                obj['tokens'] = ApiClient.convertToType(data['tokens'], ['String']);
            }
            if (data.hasOwnProperty('trialEndDate')) {
                obj['trialEndDate'] = ApiClient.convertToType(data['trialEndDate'], 'Number');
            }
            if (data.hasOwnProperty('urlGroupLimit')) {
                obj['urlGroupLimit'] = ApiClient.convertToType(data['urlGroupLimit'], 'Number');
            }
            if (data.hasOwnProperty('userRoles')) {
                obj['userRoles'] = ApiClient.convertToType(data['userRoles'], [UserRole]);
            }
            if (data.hasOwnProperty('writeToken')) {
                obj['writeToken'] = ApiClient.convertToType(data['writeToken'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} ajaxThreshold
    */
    'ajaxThreshold' = undefined;
    /**
    * @member {String} appType
    */
    'appType' = undefined;
    /**
    * @member {Number} appTypeId
    */
    'appTypeId' = undefined;
    /**
    * @member {String} creatorEmail
    */
    'creatorEmail' = undefined;
    /**
    * @member {String} creditCardExpiry
    */
    'creditCardExpiry' = undefined;
    /**
    * @member {String} creditCardNumber
    */
    'creditCardNumber' = undefined;
    /**
    * @member {String} description
    */
    'description' = undefined;
    /**
    * @member {String} displayStatus
    */
    'displayStatus' = undefined;
    /**
    * @member {Number} firstDataSavedDate
    */
    'firstDataSavedDate' = undefined;
    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {module:model/ServiceIntegration} integration
    */
    'integration' = undefined;
    /**
    * @member {Number} lastDataReceivedDate
    */
    'lastDataReceivedDate' = undefined;
    /**
    * @member {Number} lastDataSavedDate
    */
    'lastDataSavedDate' = undefined;
    /**
    * @member {String} loggedInUserAppRole
    */
    'loggedInUserAppRole' = undefined;
    /**
    * @member {Boolean} monthlyInvoiceAccount
    */
    'monthlyInvoiceAccount' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} ownerEmail
    */
    'ownerEmail' = undefined;
    /**
    * @member {module:model/BasicOrganizationDto} owningOrganization
    */
    'owningOrganization' = undefined;
    /**
    * @member {Number} pageLoadThreshold
    */
    'pageLoadThreshold' = undefined;
    /**
    * @member {Number} paymentMethodId
    */
    'paymentMethodId' = undefined;
    /**
    * @member {module:model/Plan} plan
    */
    'plan' = undefined;
    /**
    * @member {Boolean} prepaidAccount
    */
    'prepaidAccount' = undefined;
    /**
    * @member {String} readToken
    */
    'readToken' = undefined;
    /**
    * @member {String} readWriteToken
    */
    'readWriteToken' = undefined;
    /**
    * @member {Number} registrationDate
    */
    'registrationDate' = undefined;
    /**
    * @member {String} status
    */
    'status' = undefined;
    /**
    * @member {String} token
    */
    'token' = undefined;
    /**
    * @member {Array.<String>} tokens
    */
    'tokens' = undefined;
    /**
    * @member {Number} trialEndDate
    */
    'trialEndDate' = undefined;
    /**
    * @member {Number} urlGroupLimit
    */
    'urlGroupLimit' = undefined;
    /**
    * @member {Array.<module:model/UserRole>} userRoles
    */
    'userRoles' = undefined;
    /**
    * @member {String} writeToken
    */
    'writeToken' = undefined;




}
