/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient'
import { BasicOrganizationDto } from './BasicOrganizationDto'
import { Plan } from './Plan'
import { ServiceIntegration } from './ServiceIntegration'
import { UserRole } from './UserRole'

/**
 * The App model module.
 * @module model/App
 * @version 0.1.0
 */
export class App {
  /**
   * Constructs a new <code>App</code>.
   * @alias module:model/App
   * @class
   */
  constructor () {}

  /**
   * Constructs a <code>App</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/App} obj Optional instance to populate.
   * @return {module:model/App} The populated <code>App</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      obj = obj || new App()
      if (data.hasOwnProperty('ajaxThreshold'))
        // eslint-disable-line no-prototype-builtins
        obj.ajaxThreshold = ApiClient.convertToType(
          data['ajaxThreshold'],
          'Number'
        )
      if (data.hasOwnProperty('appType'))
        // eslint-disable-line no-prototype-builtins
        obj.appType = ApiClient.convertToType(data['appType'], 'String')
      if (data.hasOwnProperty('appTypeId'))
        // eslint-disable-line no-prototype-builtins
        obj.appTypeId = ApiClient.convertToType(data['appTypeId'], 'Number')
      if (data.hasOwnProperty('creatorEmail'))
        // eslint-disable-line no-prototype-builtins
        obj.creatorEmail = ApiClient.convertToType(
          data['creatorEmail'],
          'String'
        )
      if (data.hasOwnProperty('creditCardExpiry'))
        // eslint-disable-line no-prototype-builtins
        obj.creditCardExpiry = ApiClient.convertToType(
          data['creditCardExpiry'],
          'String'
        )
      if (data.hasOwnProperty('creditCardNumber'))
        // eslint-disable-line no-prototype-builtins
        obj.creditCardNumber = ApiClient.convertToType(
          data['creditCardNumber'],
          'String'
        )
      if (data.hasOwnProperty('description'))
        // eslint-disable-line no-prototype-builtins
        obj.description = ApiClient.convertToType(data['description'], 'String')
      if (data.hasOwnProperty('displayStatus'))
        // eslint-disable-line no-prototype-builtins
        obj.displayStatus = ApiClient.convertToType(
          data['displayStatus'],
          'String'
        )
      if (data.hasOwnProperty('firstDataSavedDate'))
        // eslint-disable-line no-prototype-builtins
        obj.firstDataSavedDate = ApiClient.convertToType(
          data['firstDataSavedDate'],
          'Number'
        )
      if (data.hasOwnProperty('id'))
        // eslint-disable-line no-prototype-builtins
        obj.id = ApiClient.convertToType(data['id'], 'Number')
      if (data.hasOwnProperty('integration'))
        // eslint-disable-line no-prototype-builtins
        obj.integration = ServiceIntegration.constructFromObject(
          data['integration']
        )
      if (data.hasOwnProperty('lastDataReceivedDate'))
        // eslint-disable-line no-prototype-builtins
        obj.lastDataReceivedDate = ApiClient.convertToType(
          data['lastDataReceivedDate'],
          'Number'
        )
      if (data.hasOwnProperty('lastDataSavedDate'))
        // eslint-disable-line no-prototype-builtins
        obj.lastDataSavedDate = ApiClient.convertToType(
          data['lastDataSavedDate'],
          'Number'
        )
      if (data.hasOwnProperty('loggedInUserAppRole'))
        // eslint-disable-line no-prototype-builtins
        obj.loggedInUserAppRole = ApiClient.convertToType(
          data['loggedInUserAppRole'],
          'String'
        )
      if (data.hasOwnProperty('monthlyInvoiceAccount'))
        // eslint-disable-line no-prototype-builtins
        obj.monthlyInvoiceAccount = ApiClient.convertToType(
          data['monthlyInvoiceAccount'],
          'Boolean'
        )
      if (data.hasOwnProperty('name'))
        // eslint-disable-line no-prototype-builtins
        obj.name = ApiClient.convertToType(data['name'], 'String')
      if (data.hasOwnProperty('ownerEmail'))
        // eslint-disable-line no-prototype-builtins
        obj.ownerEmail = ApiClient.convertToType(data['ownerEmail'], 'String')
      if (data.hasOwnProperty('owningOrganization'))
        // eslint-disable-line no-prototype-builtins
        obj.owningOrganization = BasicOrganizationDto.constructFromObject(
          data['owningOrganization']
        )
      if (data.hasOwnProperty('pageLoadThreshold'))
        // eslint-disable-line no-prototype-builtins
        obj.pageLoadThreshold = ApiClient.convertToType(
          data['pageLoadThreshold'],
          'Number'
        )
      if (data.hasOwnProperty('paymentMethodId'))
        // eslint-disable-line no-prototype-builtins
        obj.paymentMethodId = ApiClient.convertToType(
          data['paymentMethodId'],
          'Number'
        )
      if (data.hasOwnProperty('plan'))
        // eslint-disable-line no-prototype-builtins
        obj.plan = Plan.constructFromObject(data['plan'])
      if (data.hasOwnProperty('prepaidAccount'))
        // eslint-disable-line no-prototype-builtins
        obj.prepaidAccount = ApiClient.convertToType(
          data['prepaidAccount'],
          'Boolean'
        )
      if (data.hasOwnProperty('status'))
        // eslint-disable-line no-prototype-builtins
        obj.status = ApiClient.convertToType(data['status'], 'String')
      if (data.hasOwnProperty('token'))
        // eslint-disable-line no-prototype-builtins
        obj.token = ApiClient.convertToType(data['token'], 'String')
      if (data.hasOwnProperty('trialEndDate'))
        // eslint-disable-line no-prototype-builtins
        obj.trialEndDate = ApiClient.convertToType(
          data['trialEndDate'],
          'Number'
        )
      if (data.hasOwnProperty('urlGroupLimit'))
        // eslint-disable-line no-prototype-builtins
        obj.urlGroupLimit = ApiClient.convertToType(
          data['urlGroupLimit'],
          'Number'
        )
      if (data.hasOwnProperty('userRoles'))
        // eslint-disable-line no-prototype-builtins
        obj.userRoles = ApiClient.convertToType(data['userRoles'], [UserRole])
    }
    return obj
  }
}

/**
 * @member {Number} ajaxThreshold
 */
App.prototype.ajaxThreshold = undefined

/**
 * @member {String} appType
 */
App.prototype.appType = undefined

/**
 * @member {Number} appTypeId
 */
App.prototype.appTypeId = undefined

/**
 * @member {String} creatorEmail
 */
App.prototype.creatorEmail = undefined

/**
 * @member {String} creditCardExpiry
 */
App.prototype.creditCardExpiry = undefined

/**
 * @member {String} creditCardNumber
 */
App.prototype.creditCardNumber = undefined

/**
 * @member {String} description
 */
App.prototype.description = undefined

/**
 * @member {String} displayStatus
 */
App.prototype.displayStatus = undefined

/**
 * @member {Number} firstDataSavedDate
 */
App.prototype.firstDataSavedDate = undefined

/**
 * @member {Number} id
 */
App.prototype.id = undefined

/**
 * @member {module:model/ServiceIntegration} integration
 */
App.prototype.integration = undefined

/**
 * @member {Number} lastDataReceivedDate
 */
App.prototype.lastDataReceivedDate = undefined

/**
 * @member {Number} lastDataSavedDate
 */
App.prototype.lastDataSavedDate = undefined

/**
 * @member {String} loggedInUserAppRole
 */
App.prototype.loggedInUserAppRole = undefined

/**
 * @member {Boolean} monthlyInvoiceAccount
 */
App.prototype.monthlyInvoiceAccount = undefined

/**
 * @member {String} name
 */
App.prototype.name = undefined

/**
 * @member {String} ownerEmail
 */
App.prototype.ownerEmail = undefined

/**
 * @member {module:model/BasicOrganizationDto} owningOrganization
 */
App.prototype.owningOrganization = undefined

/**
 * @member {Number} pageLoadThreshold
 */
App.prototype.pageLoadThreshold = undefined

/**
 * @member {Number} paymentMethodId
 */
App.prototype.paymentMethodId = undefined

/**
 * @member {module:model/Plan} plan
 */
App.prototype.plan = undefined

/**
 * @member {Boolean} prepaidAccount
 */
App.prototype.prepaidAccount = undefined

/**
 * @member {String} status
 */
App.prototype.status = undefined

/**
 * @member {String} token
 */
App.prototype.token = undefined

/**
 * @member {Number} trialEndDate
 */
App.prototype.trialEndDate = undefined

/**
 * @member {Number} urlGroupLimit
 */
App.prototype.urlGroupLimit = undefined

/**
 * @member {Array.<module:model/UserRole>} userRoles
 */
App.prototype.userRoles = undefined
