/**
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The BillingInfo model module.
* @module model/BillingInfo
* @version 0.1.0
*/
export default class BillingInfo {
    /**
    * Constructs a new <code>BillingInfo</code>.
    * @alias module:model/BillingInfo
    * @class
    */

    constructor() {



    }

    /**
    * Constructs a <code>BillingInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BillingInfo} obj Optional instance to populate.
    * @return {module:model/BillingInfo} The populated <code>BillingInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BillingInfo();


            if (data.hasOwnProperty('creditCardId')) {
                obj['creditCardId'] = ApiClient.convertToType(data['creditCardId'], 'Number');
            }
            if (data.hasOwnProperty('paymentMethod')) {
                obj['paymentMethod'] = ApiClient.convertToType(data['paymentMethod'], 'String');
            }
            if (data.hasOwnProperty('planId')) {
                obj['planId'] = ApiClient.convertToType(data['planId'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} creditCardId
    */
    'creditCardId' = undefined;
    /**
    * @member {String} paymentMethod
    */
    'paymentMethod' = undefined;
    /**
    * @member {Number} planId
    */
    'planId' = undefined;




}
