/**
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../api/ApiClient.js'
import App from './App.js'
import DayUsageData from './DayUsageData.js'
import MinPeriodFeePeriod from './MinPeriodFeePeriod.js'

/**
* The ChargesDetailsResponseDto model module.
* @module model/ChargesDetailsResponseDto
* @version 0.1.0
*/
export default class ChargesDetailsResponseDto {
  /**
    * Constructs a new <code>ChargesDetailsResponseDto</code>.
    * @alias module:model/ChargesDetailsResponseDto
    * @class
    */

  constructor() {



  }

  /**
    * Constructs a <code>ChargesDetailsResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ChargesDetailsResponseDto} obj Optional instance to populate.
    * @return {module:model/ChargesDetailsResponseDto} The populated <code>ChargesDetailsResponseDto</code> instance.
    */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChargesDetailsResponseDto()


      if (Object.prototype.hasOwnProperty.call(data,'app')) {
        obj['app'] = App.constructFromObject(data['app'])
      }
      if (Object.prototype.hasOwnProperty.call(data,'chargeBase')) {
        obj['chargeBase'] = ApiClient.convertToType(data['chargeBase'], 'String')
      }
      if (Object.prototype.hasOwnProperty.call(data,'dayUsageData')) {
        obj['dayUsageData'] = ApiClient.convertToType(data['dayUsageData'], [DayUsageData])
      }
      if (Object.prototype.hasOwnProperty.call(data,'monthlyFeeAmount')) {
        obj['monthlyFeeAmount'] = ApiClient.convertToType(data['monthlyFeeAmount'], 'Number')
      }
      if (Object.prototype.hasOwnProperty.call(data,'periodFeePeriods')) {
        obj['periodFeePeriods'] = ApiClient.convertToType(data['periodFeePeriods'], [MinPeriodFeePeriod])
      }
      if (Object.prototype.hasOwnProperty.call(data,'totalAmount')) {
        obj['totalAmount'] = ApiClient.convertToType(data['totalAmount'], 'Number')
      }
      if (Object.prototype.hasOwnProperty.call(data,'usageAmount')) {
        obj['usageAmount'] = ApiClient.convertToType(data['usageAmount'], 'Number')
      }
    }
    return obj
  }

    /**
    * @member {module:model/App} app
    */
    'app' = undefined;
    /**
    * @member {module:model/ChargesDetailsResponseDto.ChargeBaseEnum} chargeBase
    */
    'chargeBase' = undefined;
    /**
    * @member {Array.<module:model/DayUsageData>} dayUsageData
    */
    'dayUsageData' = undefined;
    /**
    * @member {Number} monthlyFeeAmount
    */
    'monthlyFeeAmount' = undefined;
    /**
    * @member {Array.<module:model/MinPeriodFeePeriod>} periodFeePeriods
    */
    'periodFeePeriods' = undefined;
    /**
    * @member {Number} totalAmount
    */
    'totalAmount' = undefined;
    /**
    * @member {Number} usageAmount
    */
    'usageAmount' = undefined;



    /**
    * Allowed values for the <code>chargeBase</code> property.
    * @enum {String}
    * @readonly
    */
    static ChargeBaseEnum = {
      /**
         * value: "SUMMARIZED_USAGE"
         * @const
         */
      'SUMMARIZED_USAGE': 'SUMMARIZED_USAGE',
      /**
         * value: "MIN_MONTHLY_FEE"
         * @const
         */
      'MIN_MONTHLY_FEE': 'MIN_MONTHLY_FEE',
      /**
         * value: "SUM_OF_DAILY_FEES"
         * @const
         */
      'SUM_OF_DAILY_FEES': 'SUM_OF_DAILY_FEES',
      /**
         * value: "TOTAL_MONTHLY_FEE"
         * @const
         */
      'TOTAL_MONTHLY_FEE': 'TOTAL_MONTHLY_FEE'
    };

}
