/**
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The DailyDto model module.
* @module model/DailyDto
* @version 0.1.0
*/
export default class DailyDto {
    /**
    * Constructs a new <code>DailyDto</code>.
    * @alias module:model/DailyDto
    * @class
    */

    constructor() {



    }

    /**
    * Constructs a <code>DailyDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DailyDto} obj Optional instance to populate.
    * @return {module:model/DailyDto} The populated <code>DailyDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DailyDto();


            if (data.hasOwnProperty('day')) {
                obj['day'] = ApiClient.convertToType(data['day'], 'Number');
            }
            if (data.hasOwnProperty('failed')) {
                obj['failed'] = ApiClient.convertToType(data['failed'], 'Number');
            }
            if (data.hasOwnProperty('indexed')) {
                obj['indexed'] = ApiClient.convertToType(data['indexed'], 'Number');
            }
            if (data.hasOwnProperty('volume')) {
                obj['volume'] = ApiClient.convertToType(data['volume'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} day
    */
    'day' = undefined;
    /**
    * @member {Number} failed
    */
    'failed' = undefined;
    /**
    * @member {Number} indexed
    */
    'indexed' = undefined;
    /**
    * @member {Number} volume
    */
    'volume' = undefined;




}
