/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient'
import { DataSeriesFilter } from './DataSeriesFilter'

/**
 * The DataSeriesRequest model module.
 * @module model/DataSeriesRequest
  */
export class DataSeriesRequest {
  /**
   * Constructs a new <code>DataSeriesRequest</code>.
   * @alias module:model/DataSeriesRequest
   * @class
   * @param metric {String} Metric name or metric group prefix
   */
  constructor(metric) {
    this.metric = metric
  }

  /**
   * Constructs a <code>DataSeriesRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DataSeriesRequest} obj Optional instance to populate.
   * @return {module:model/DataSeriesRequest} The populated <code>DataSeriesRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DataSeriesRequest()
      if (data.hasOwnProperty('defaultInterval'))
        // eslint-disable-line no-prototype-builtins
        obj.defaultInterval = ApiClient.convertToType(
          data['defaultInterval'],
          'Number'
        )
      if (data.hasOwnProperty('end'))
        // eslint-disable-line no-prototype-builtins
        obj.end = ApiClient.convertToType(data['end'], 'String')
      if (data.hasOwnProperty('filters'))
        // eslint-disable-line no-prototype-builtins
        obj.filters = ApiClient.convertToType(data['filters'], {
          String: DataSeriesFilter
        })
      if (data.hasOwnProperty('granularity'))
        // eslint-disable-line no-prototype-builtins
        obj.granularity = ApiClient.convertToType(data['granularity'], 'String')
      if (data.hasOwnProperty('interval'))
        // eslint-disable-line no-prototype-builtins
        obj.interval = ApiClient.convertToType(data['interval'], 'String')
      if (data.hasOwnProperty('metric'))
        // eslint-disable-line no-prototype-builtins
        obj.metric = ApiClient.convertToType(data['metric'], 'String')
      if (data.hasOwnProperty('start'))
        // eslint-disable-line no-prototype-builtins
        obj.start = ApiClient.convertToType(data['start'], 'String')
    }
    return obj
  }
}

/**
 * @member {Number} defaultInterval
 */
DataSeriesRequest.prototype.defaultInterval = undefined

/**
 * End time of interval. Can be expressed as timestamp in milliseconds or UTC date in yyyy-MM-dd HH:mm:ss format
 * @member {String} end
 */
DataSeriesRequest.prototype.end = undefined

/**
 * Map of allowed filter values and aggregation strategy. List of available filter values can be fetched using metric filters endpoint and default aggregation strategy depends on metric
 * @member {Object.<String, module:model/DataSeriesFilter>} filters
 */
DataSeriesRequest.prototype.filters = undefined

/**
 * Allowed values for the <code>granularity</code> property.
 * @enum {String}
 * @readonly
 */
DataSeriesRequest.GranularityEnum = {
  /**
   * value: "AUTO"
   * @const
   */
  AUTO: 'AUTO',

  /**
   * value: "ONE_MINUTE"
   * @const
   */
  ONE_MINUTE: 'ONE_MINUTE',

  /**
   * value: "FIVE_MINUTES"
   * @const
   */
  FIVE_MINUTES: 'FIVE_MINUTES',

  /**
   * value: "HOUR"
   * @const
   */
  HOUR: 'HOUR',

  /**
   * value: "DAY"
   * @const
   */
  DAY: 'DAY',

  /**
   * value: "WEEK"
   * @const
   */
  WEEK: 'WEEK',

  /**
   * value: "MONTH"
   * @const
   */
  MONTH: 'MONTH'
}

/**
 * Data points interval granularity between two data points.Default value is \"AUTO\" - calculated based on selected time span. Not required while getting filters.
 * @member {module:model/DataSeriesRequest.GranularityEnum} granularity
 */
DataSeriesRequest.prototype.granularity = undefined

/**
 * @member {String} interval
 */
DataSeriesRequest.prototype.interval = undefined

/**
 * Metric name or metric group prefix
 * @member {String} metric
 */
DataSeriesRequest.prototype.metric = undefined

/**
 * Start time of interval. Can be expressed as timestamp in milliseconds or UTC date in yyyy-MM-dd HH:mm:ss format
 * @member {String} start
 */
DataSeriesRequest.prototype.start = undefined
