/**
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The DayUsageData model module.
* @module model/DayUsageData
* @version 0.1.0
*/
export default class DayUsageData {
    /**
    * Constructs a new <code>DayUsageData</code>.
    * @alias module:model/DayUsageData
    * @class
    */

    constructor() {



    }

    /**
    * Constructs a <code>DayUsageData</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DayUsageData} obj Optional instance to populate.
    * @return {module:model/DayUsageData} The populated <code>DayUsageData</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DayUsageData();


            if (data.hasOwnProperty('countDailyDataPoints')) {
                obj['countDailyDataPoints'] = ApiClient.convertToType(data['countDailyDataPoints'], 'Number');
            }
            if (data.hasOwnProperty('day')) {
                obj['day'] = ApiClient.convertToType(data['day'], 'String');
            }
            if (data.hasOwnProperty('discount')) {
                obj['discount'] = ApiClient.convertToType(data['discount'], 'Number');
            }
            if (data.hasOwnProperty('dpmPerContainerHostQuota')) {
                obj['dpmPerContainerHostQuota'] = ApiClient.convertToType(data['dpmPerContainerHostQuota'], 'Number');
            }
            if (data.hasOwnProperty('dpmPerHostQuota')) {
                obj['dpmPerHostQuota'] = ApiClient.convertToType(data['dpmPerHostQuota'], 'Number');
            }
            if (data.hasOwnProperty('fixedMonthlyPrice')) {
                obj['fixedMonthlyPrice'] = ApiClient.convertToType(data['fixedMonthlyPrice'], 'Number');
            }
            if (data.hasOwnProperty('fixedMonthlyPricePerHour')) {
                obj['fixedMonthlyPricePerHour'] = ApiClient.convertToType(data['fixedMonthlyPricePerHour'], 'Number');
            }
            if (data.hasOwnProperty('freeContainersPerHost')) {
                obj['freeContainersPerHost'] = ApiClient.convertToType(data['freeContainersPerHost'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('kiloDpmOveragePricePerHour')) {
                obj['kiloDpmOveragePricePerHour'] = ApiClient.convertToType(data['kiloDpmOveragePricePerHour'], 'Number');
            }
            if (data.hasOwnProperty('planType')) {
                obj['planType'] = ApiClient.convertToType(data['planType'], 'String');
            }
            if (data.hasOwnProperty('pricePerContainerHostHour')) {
                obj['pricePerContainerHostHour'] = ApiClient.convertToType(data['pricePerContainerHostHour'], 'Number');
            }
            if (data.hasOwnProperty('pricePerContainerHour')) {
                obj['pricePerContainerHour'] = ApiClient.convertToType(data['pricePerContainerHour'], 'Number');
            }
            if (data.hasOwnProperty('pricePerServerHour')) {
                obj['pricePerServerHour'] = ApiClient.convertToType(data['pricePerServerHour'], 'Number');
            }
            if (data.hasOwnProperty('sumNumberOfContainerHosts')) {
                obj['sumNumberOfContainerHosts'] = ApiClient.convertToType(data['sumNumberOfContainerHosts'], 'Number');
            }
            if (data.hasOwnProperty('sumNumberOfContainers')) {
                obj['sumNumberOfContainers'] = ApiClient.convertToType(data['sumNumberOfContainers'], 'Number');
            }
            if (data.hasOwnProperty('sumNumberOfServers')) {
                obj['sumNumberOfServers'] = ApiClient.convertToType(data['sumNumberOfServers'], 'Number');
            }
            if (data.hasOwnProperty('usageAmount')) {
                obj['usageAmount'] = ApiClient.convertToType(data['usageAmount'], 'Number');
            }
            if (data.hasOwnProperty('usedPlan')) {
                obj['usedPlan'] = ApiClient.convertToType(data['usedPlan'], 'String');
            }
            if (data.hasOwnProperty('userDiscount')) {
                obj['userDiscount'] = ApiClient.convertToType(data['userDiscount'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} countDailyDataPoints
    */
    'countDailyDataPoints' = undefined;
    /**
    * @member {String} day
    */
    'day' = undefined;
    /**
    * @member {Number} discount
    */
    'discount' = undefined;
    /**
    * @member {Number} dpmPerContainerHostQuota
    */
    'dpmPerContainerHostQuota' = undefined;
    /**
    * @member {Number} dpmPerHostQuota
    */
    'dpmPerHostQuota' = undefined;
    /**
    * @member {Number} fixedMonthlyPrice
    */
    'fixedMonthlyPrice' = undefined;
    /**
    * @member {Number} fixedMonthlyPricePerHour
    */
    'fixedMonthlyPricePerHour' = undefined;
    /**
    * @member {Number} freeContainersPerHost
    */
    'freeContainersPerHost' = undefined;
    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {Number} kiloDpmOveragePricePerHour
    */
    'kiloDpmOveragePricePerHour' = undefined;
    /**
    * @member {module:model/DayUsageData.PlanTypeEnum} planType
    */
    'planType' = undefined;
    /**
    * @member {Number} pricePerContainerHostHour
    */
    'pricePerContainerHostHour' = undefined;
    /**
    * @member {Number} pricePerContainerHour
    */
    'pricePerContainerHour' = undefined;
    /**
    * @member {Number} pricePerServerHour
    */
    'pricePerServerHour' = undefined;
    /**
    * @member {Number} sumNumberOfContainerHosts
    */
    'sumNumberOfContainerHosts' = undefined;
    /**
    * @member {Number} sumNumberOfContainers
    */
    'sumNumberOfContainers' = undefined;
    /**
    * @member {Number} sumNumberOfServers
    */
    'sumNumberOfServers' = undefined;
    /**
    * @member {Number} usageAmount
    */
    'usageAmount' = undefined;
    /**
    * @member {String} usedPlan
    */
    'usedPlan' = undefined;
    /**
    * @member {Number} userDiscount
    */
    'userDiscount' = undefined;



    /**
    * Allowed values for the <code>planType</code> property.
    * @enum {String}
    * @readonly
    */
    static PlanTypeEnum = {
        /**
         * value: "INFRA"
         * @const
         */
        "INFRA": "INFRA",
        /**
         * value: "PER_AGENT"
         * @const
         */
        "PER_AGENT": "PER_AGENT",
        /**
         * value: "FIXED_PRICE"
         * @const
         */
        "FIXED_PRICE": "FIXED_PRICE",
        /**
         * value: "PER_VOLUME"
         * @const
         */
        "PER_VOLUME": "PER_VOLUME"
    };

}
