/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient'

/**
 * The EventDto model module.
 * @module model/EventDto
 * @version 0.4.0
 */
export class EventDto {
  /**
   * Constructs a new <code>EventDto</code>.
   * @alias module:model/EventDto
   * @class
   */
  constructor () {}

  /**
   * Constructs a <code>EventDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventDto} obj Optional instance to populate.
   * @return {module:model/EventDto} The populated <code>EventDto</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      obj = obj || new EventDto()
      if (data.hasOwnProperty('from'))
        obj.from = ApiClient.convertToType(data['from'], Object)
      if (data.hasOwnProperty('to'))
        obj.to = ApiClient.convertToType(data['to'], Object)
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String')
    }
    return obj
  }
}

/**
 * @member {Object} from
 */
EventDto.prototype.from = undefined

/**
 * @member {Object} to
 */
EventDto.prototype.to = undefined

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
EventDto.TypeEnum = {
  /**
   * value: "CREATED"
   * @const
   */
  CREATED: 'CREATED',

  /**
   * value: "DISABLED"
   * @const
   */
  DISABLED: 'DISABLED',

  /**
   * value: "DELETED"
   * @const
   */
  DELETED: 'DELETED',

  /**
   * value: "REACTIVATED"
   * @const
   */
  REACTIVATED: 'REACTIVATED',

  /**
   * value: "PLAN_UPDATE"
   * @const
   */
  PLAN_UPDATE: 'PLAN_UPDATE',

  /**
   * value: "PAYMENT_METHOD_UPDATE"
   * @const
   */
  PAYMENT_METHOD_UPDATE: 'PAYMENT_METHOD_UPDATE',

  /**
   * value: "SEND_EMAIL_CHANGE"
   * @const
   */
  SEND_EMAIL_CHANGE: 'SEND_EMAIL_CHANGE',

  /**
   * value: "AUTOMATIC_PLAN_UPGRADE_CHANGE"
   * @const
   */
  AUTOMATIC_PLAN_UPGRADE_CHANGE: 'AUTOMATIC_PLAN_UPGRADE_CHANGE',

  /**
   * value: "MAX_LIMIT_CHANGE"
   * @const
   */
  MAX_LIMIT_CHANGE: 'MAX_LIMIT_CHANGE',

  /**
   * value: "SAMPLING_CHANGE"
   * @const
   */
  SAMPLING_CHANGE: 'SAMPLING_CHANGE',

  /**
   * value: "OWNERSHIP_CHANGE"
   * @const
   */
  OWNERSHIP_CHANGE: 'OWNERSHIP_CHANGE',

  /**
   * value: "PIPELINE_CHANGE"
   * @const
   */
  PIPELINE_CHANGE: 'PIPELINE_CHANGE'
}
/**
 * @member {module:model/EventDto.TypeEnum} type
 */
EventDto.prototype.type = undefined
