/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient'
import {Error} from './Error'

/**
 * The GenericApiResponse model module.
 * @module model/GenericApiResponse
 * @version 0.1.0
 */
export class GenericApiResponse {
  /**
   * Constructs a new <code>GenericApiResponse</code>.
   * Generic wrapper class for all API responses
   * @alias module:model/GenericApiResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GenericApiResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GenericApiResponse} obj Optional instance to populate.
   * @return {module:model/GenericApiResponse} The populated <code>GenericApiResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GenericApiResponse()
      if (data.hasOwnProperty('data')) // eslint-disable-line no-prototype-builtins
        obj.data = ApiClient.convertToType(data['data'], Object)
      if (data.hasOwnProperty('errors')) // eslint-disable-line no-prototype-builtins
        obj.errors = ApiClient.convertToType(data['errors'], [Error])
      if (data.hasOwnProperty('message')) // eslint-disable-line no-prototype-builtins
        obj.message = ApiClient.convertToType(data['message'], 'String')
      if (data.hasOwnProperty('success')) // eslint-disable-line no-prototype-builtins
        obj.success = ApiClient.convertToType(data['success'], 'Boolean')
    }
    return obj
  }
}

/**
 * Contains actual data when response is successful. Key and Value is specific to each endpoint
 * @member {Object} data
 */
GenericApiResponse.prototype.data = undefined

/**
 * @member {Array.<module:model/Error>} errors
 */
GenericApiResponse.prototype.errors = undefined

/**
 * @member {String} message
 */
GenericApiResponse.prototype.message = undefined

/**
 * @member {Boolean} success
 */
GenericApiResponse.prototype.success = undefined
