/**
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../api/ApiClient.js'

/**
* The LimitChangeEventDTO model module.
* @module model/LimitChangeEventDTO
* @version 0.1.0
*/
export default class LimitChangeEventDTO {
  /**
    * Constructs a new <code>LimitChangeEventDTO</code>.
    * @alias module:model/LimitChangeEventDTO
    * @class
    */

  constructor() {



  }

  /**
    * Constructs a <code>LimitChangeEventDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LimitChangeEventDTO} obj Optional instance to populate.
    * @return {module:model/LimitChangeEventDTO} The populated <code>LimitChangeEventDTO</code> instance.
    */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LimitChangeEventDTO()


      if (Object.prototype.hasOwnProperty.call(data,'eventTime')) {
        obj['eventTime'] = ApiClient.convertToType(data['eventTime'], 'Date')
      }
      if (Object.prototype.hasOwnProperty.call(data,'newLimit')) {
        obj['newLimit'] = ApiClient.convertToType(data['newLimit'], 'Number')
      }
      if (Object.prototype.hasOwnProperty.call(data,'oldLimit')) {
        obj['oldLimit'] = ApiClient.convertToType(data['oldLimit'], 'Number')
      }
    }
    return obj
  }

    /**
    * @member {Date} eventTime
    */
    'eventTime' = undefined;
    /**
    * @member {Number} newLimit
    */
    'newLimit' = undefined;
    /**
    * @member {Number} oldLimit
    */
    'oldLimit' = undefined;




}
