/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from '../ApiClient'
import { Error } from './Error'
import { PlansResponseEntry } from './PlansResponseEntry'

/**
 * The PlansResponse model module.
 * @module model/PlansResponse
 * @version 0.4.0
 */
export class PlansResponse {
  /**
   * Constructs a new <code>PlansResponse</code>.
   * @alias module:model/PlansResponse
   * @class
   */
  constructor () {}

  /**
   * Constructs a <code>PlansResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PlansResponse} obj Optional instance to populate.
   * @return {module:model/PlansResponse} The populated <code>PlansResponse</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      obj = obj || new PlansResponse()
      if (data.hasOwnProperty('data'))
        obj.data = PlansResponseEntry.constructFromObject(data['data'])
      if (data.hasOwnProperty('errors'))
        obj.errors = ApiClient.convertToType(data['errors'], [Error])
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String')
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean')
    }
    return obj
  }
}

/**
 * @member {module:model/PlansResponseEntry} data
 */
PlansResponse.prototype.data = undefined

/**
 * @member {Array.<module:model/Error>} errors
 */
PlansResponse.prototype.errors = undefined

/**
 * @member {String} message
 */
PlansResponse.prototype.message = undefined

/**
 * @member {Boolean} success
 */
PlansResponse.prototype.success = undefined
