/**
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../api/ApiClient.js'
import Subscription from './Subscription.js'

/**
* The SubscriptionsResponseEntry model module.
* @module model/SubscriptionsResponseEntry
* @version 0.1.0
*/
export default class SubscriptionsResponseEntry {
  /**
    * Constructs a new <code>SubscriptionsResponseEntry</code>.
    * @alias module:model/SubscriptionsResponseEntry
    * @class
    */

  constructor() {



  }

  /**
    * Constructs a <code>SubscriptionsResponseEntry</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SubscriptionsResponseEntry} obj Optional instance to populate.
    * @return {module:model/SubscriptionsResponseEntry} The populated <code>SubscriptionsResponseEntry</code> instance.
    */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubscriptionsResponseEntry()


      if (Object.prototype.hasOwnProperty.call(data,'subscriptions')) {
        obj['subscriptions'] = ApiClient.convertToType(data['subscriptions'], [Subscription])
      }
    }
    return obj
  }

    /**
    * @member {Array.<module:model/Subscription>} subscriptions
    */
    'subscriptions' = undefined;




}
