/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TagsGrouped} from './TagsGrouped';

/**
 * The TagsGroupedResponse model module.
 * @module model/TagsGroupedResponse
 * @version 0.5.0
 */
export class TagsGroupedResponse {
  /**
   * Constructs a new <code>TagsGroupedResponse</code>.
   * @alias module:model/TagsGroupedResponse
   * @class
   * @param v {Array.<module:model/TagsGrouped>} 
   */
  constructor(v) {
    this.v = v;
  }

  /**
   * Constructs a <code>TagsGroupedResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TagsGroupedResponse} obj Optional instance to populate.
   * @return {module:model/TagsGroupedResponse} The populated <code>TagsGroupedResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TagsGroupedResponse();
      if (data.hasOwnProperty('v'))
        obj.v = ApiClient.convertToType(data['v'], [TagsGrouped]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/TagsGrouped>} v
 */
TagsGroupedResponse.prototype.v = undefined;

