/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Dimension} from './Dimension';

/**
 * The TagsGrouped model module.
 * @module model/TagsGrouped
 * @version 0.5.0
 */
export class TagsGrouped {
  /**
   * Constructs a new <code>TagsGrouped</code>.
   * @alias module:model/TagsGrouped
   * @class
   * @param appId {Number} 
   * @param tags {Object.<String, module:model/Dimension>} 
   */
  constructor(appId, tags) {
    this.appId = appId;
    this.tags = tags;
  }

  /**
   * Constructs a <code>TagsGrouped</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TagsGrouped} obj Optional instance to populate.
   * @return {module:model/TagsGrouped} The populated <code>TagsGrouped</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TagsGrouped();
      if (data.hasOwnProperty('appId'))
        obj.appId = ApiClient.convertToType(data['appId'], 'Number');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], {'String': Dimension});
    }
    return obj;
  }
}

/**
 * @member {Number} appId
 */
TagsGrouped.prototype.appId = undefined;

/**
 * @member {Object.<String, module:model/Dimension>} tags
 */
TagsGrouped.prototype.tags = undefined;

