/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../stcloud/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../stcloud/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SematextApiClientJavascript);
  }
}(this, function(expect, SematextApiClientJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SematextApiClientJavascript.AppsApi();
  });

  describe('(package)', function() {
    describe('AppsApi', function() {
      describe('deleteUsingDELETE', function() {
        it('should call deleteUsingDELETE successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteUsingDELETE call and complete the assertions
          /*

          instance.deleteUsingDELETE(anyStateAppId).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SematextApiClientJavascript.GenericMapBasedApiResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAppTypesUsingGET', function() {
        it('should call getAppTypesUsingGET successfully', function(done) {
          // TODO: uncomment getAppTypesUsingGET call and complete the assertions
          /*

          instance.getAppTypesUsingGET().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SematextApiClientJavascript.AppTypesResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getUsingGET', function() {
        it('should call getUsingGET successfully', function(done) {
          // TODO: uncomment, update parameter values for getUsingGET call and complete the assertions
          /*

          instance.getUsingGET(anyStateAppId).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SematextApiClientJavascript.AppResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('inviteAppGuestsUsingPOST1', function() {
        it('should call inviteAppGuestsUsingPOST1 successfully', function(done) {
          // TODO: uncomment, update parameter values for inviteAppGuestsUsingPOST1 call and complete the assertions
          /*

          instance.inviteAppGuestsUsingPOST1(body).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SematextApiClientJavascript.GenericMapBasedApiResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listAppsUsersUsingGET1', function() {
        it('should call listAppsUsersUsingGET1 successfully', function(done) {
          // TODO: uncomment listAppsUsersUsingGET1 call and complete the assertions
          /*

          instance.listAppsUsersUsingGET1().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SematextApiClientJavascript.AppsResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listUsingGET', function() {
        it('should call listUsingGET successfully', function(done) {
          // TODO: uncomment listUsingGET call and complete the assertions
          /*

          instance.listUsingGET().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SematextApiClientJavascript.AppsResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateDescriptionUsingPUT1', function() {
        it('should call updateDescriptionUsingPUT1 successfully', function(done) {
          // TODO: uncomment, update parameter values for updateDescriptionUsingPUT1 call and complete the assertions
          /*
          var opts = {};

          instance.updateDescriptionUsingPUT1(anyStateAppId, opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SematextApiClientJavascript.AppResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateUsingPUT3', function() {
        it('should call updateUsingPUT3 successfully', function(done) {
          // TODO: uncomment, update parameter values for updateUsingPUT3 call and complete the assertions
          /*

          instance.updateUsingPUT3(body, anyStateAppId).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SematextApiClientJavascript.AppResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
